/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NpcsRouteImport } from './routes/npcs'
import { Route as LootRouteImport } from './routes/loot'
import { Route as EncountersRouteImport } from './routes/encounters'
import { Route as IndexRouteImport } from './routes/index'

const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsRoute = NpcsRouteImport.update({
  id: '/npcs',
  path: '/npcs',
  getParentRoute: () => rootRouteImport,
} as any)
const LootRoute = LootRouteImport.update({
  id: '/loot',
  path: '/loot',
  getParentRoute: () => rootRouteImport,
} as any)
const EncountersRoute = EncountersRouteImport.update({
  id: '/encounters',
  path: '/encounters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encounters': typeof EncountersRoute
  '/loot': typeof LootRoute
  '/npcs': typeof NpcsRoute
  '/search': typeof SearchRoute
  '/shops': typeof ShopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encounters': typeof EncountersRoute
  '/loot': typeof LootRoute
  '/npcs': typeof NpcsRoute
  '/search': typeof SearchRoute
  '/shops': typeof ShopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/encounters': typeof EncountersRoute
  '/loot': typeof LootRoute
  '/npcs': typeof NpcsRoute
  '/search': typeof SearchRoute
  '/shops': typeof ShopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/encounters' | '/loot' | '/npcs' | '/search' | '/shops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/encounters' | '/loot' | '/npcs' | '/search' | '/shops'
  id:
    | '__root__'
    | '/'
    | '/encounters'
    | '/loot'
    | '/npcs'
    | '/search'
    | '/shops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncountersRoute: typeof EncountersRoute
  LootRoute: typeof LootRoute
  NpcsRoute: typeof NpcsRoute
  SearchRoute: typeof SearchRoute
  ShopsRoute: typeof ShopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs': {
      id: '/npcs'
      path: '/npcs'
      fullPath: '/npcs'
      preLoaderRoute: typeof NpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loot': {
      id: '/loot'
      path: '/loot'
      fullPath: '/loot'
      preLoaderRoute: typeof LootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounters': {
      id: '/encounters'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof EncountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncountersRoute: EncountersRoute,
  LootRoute: LootRoute,
  NpcsRoute: NpcsRoute,
  SearchRoute: SearchRoute,
  ShopsRoute: ShopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
